# Generated by Django 2.2.3 on 2019-08-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='work',
        ),
        migrations.AddField(
            model_name='category',
            name='work',
            field=models.ManyToManyField(to='portfolio.Work'),
        ),
    ]
