# Generated by Django 2.2.3 on 2019-08-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190801_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='work',
            new_name='works',
        ),
        migrations.RenameField(
            model_name='tech',
            old_name='work',
            new_name='works',
        ),
    ]
