version: '3'

services:
  api:
    image: gloompi/ultron-api
    build:
      context: ./ultron-api
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/usr/app/static
      - media_volume:/usr/app/media
      - ./ultron-api:/usr/app
    env_file: ./ultron-api/.env
    depends_on:
      - postgres_db
      - nginx
    environment:
      - DEBUG=1
      - SECRET_KEY='3^z(f63u+-lzxt_4nq5%a&@28)j!zh7v)j(2hp42ad$k8a!qfu'
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=ultron_db
      - SQL_USER=gloompique
      - SQL_PASSWORD=gloompiqueUltronDatabase
      - SQL_HOST=postgres_db
      - SQL_PORT=5432
  frontend:
    image: gloompi/ultron-front
    build:
      context: ./ultron-front
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./ultron-front:/usr/app
    depends_on:
      - api
      - nginx
  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.db
  nginx:
    image: gloompi/ultron-nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./ultron-nginx
    ports:
      - '80:80'

volumes:
  postgres_data:
  static_volume:
  media_volume:
