version: '3'

services:
  api:
    image: gloompi/ultron-api
    build:
      context: ./ultron-api
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/usr/app/static
      - media_volume:/usr/app/media
      - ./ultron-api:/usr/app
    env_file: ./ultron-api/.env
    depends_on:
      - postgres_db
      - nginx
  frontend:
    image: gloompi/ultron-front
    build:
      context: ./ultron-front
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./ultron-front:/usr/app
    depends_on:
      - api
      - nginx
  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.db
  nginx:
    image: gloompi/ultron-nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./ultron-nginx
    ports:
      - '80:80'

volumes:
  postgres_data:
  static_volume:
  media_volume:
