# Generated by Django 2.2.3 on 2019-08-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advantages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='icon',
            field=models.CharField(max_length=25),
        ),
    ]
