# Generated by Django 2.2.3 on 2019-08-01 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advantages', '0002_auto_20190801_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='advantages.AdvantagesSection'),
        ),
    ]
