# Generated by Django 2.2.3 on 2019-08-01 20:50

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('description', tinymce.models.HTMLField()),
                ('knowledge_percent', models.IntegerField()),
                ('skills_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='professional_skills.SkillsSection')),
            ],
        ),
    ]
