# Generated by Django 2.2.3 on 2019-07-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('background_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
