# Generated by Django 2.2.3 on 2019-07-31 20:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
