# Generated by Django 2.2.3 on 2019-08-01 10:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'About',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=30)),
                ('description', tinymce.models.HTMLField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='about.About')),
            ],
        ),
    ]
